-- 학생 세션에 STUDENT_ID를 넣고, 선택된 접근권한은 비울 수 있게 한다.
-- 일반 로그인 OTP는 초대 OTP와 분리된 TB_STUDENT_LOGIN_VERIFICATION에 둔다.
-- 기존 세션 행은 지우지 않는다.
-- 순서대로 한 번만 실행한다.

ALTER TABLE TB_STUDENT_ACCESS_SESSION ADD (STUDENT_ID NUMBER);

UPDATE TB_STUDENT_ACCESS_SESSION session_row
SET STUDENT_ID = (
    SELECT relation.STUDENT_ID
    FROM TB_TEACHER_STUDENT_ACCESS access_row
    JOIN TB_TEACHER_STUDENT relation
      ON relation.TEACHER_STUDENT_ID = access_row.TEACHER_STUDENT_ID
    WHERE access_row.TEACHER_STUDENT_ACCESS_ID = session_row.TEACHER_STUDENT_ACCESS_ID
)
WHERE session_row.STUDENT_ID IS NULL;

-- 여기서 NULL이 남아 있으면 02_verify.sql이 실패한다. NOT NULL로 바꾸기 전에 확인한다.
ALTER TABLE TB_STUDENT_ACCESS_SESSION MODIFY (STUDENT_ID NOT NULL);

ALTER TABLE TB_STUDENT_ACCESS_SESSION MODIFY (TEACHER_STUDENT_ACCESS_ID NULL);

ALTER TABLE TB_STUDENT_ACCESS_SESSION
    ADD CONSTRAINT FK_SAS_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES TB_STUDENT (STUDENT_ID);

CREATE INDEX IDX_SAS_STUDENT_ID ON TB_STUDENT_ACCESS_SESSION (STUDENT_ID);

CREATE SEQUENCE SEQ_STUDENT_LOGIN_VERIFICATION START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE TB_STUDENT_LOGIN_VERIFICATION (
    VERIFICATION_ID        NUMBER         NOT NULL,
    STUDENT_ID             NUMBER         NOT NULL,
    EMAIL_HASH             VARCHAR2(64)   NOT NULL,
    CODE_HASH              VARCHAR2(64)   NOT NULL,
    VERIFICATION_STATUS    VARCHAR2(20)   NOT NULL,
    FAILED_ATTEMPT_COUNT   NUMBER         NOT NULL,
    EXPIRES_AT             TIMESTAMP      NOT NULL,
    CONSUMED_AT            TIMESTAMP      NULL,
    INVALIDATED_AT         TIMESTAMP      NULL,
    LOCKED_UNTIL           TIMESTAMP      NULL,
    CREATED_AT             TIMESTAMP      NOT NULL,
    UPDATED_AT             TIMESTAMP      NOT NULL,
    CONSTRAINT PK_STUDENT_LOGIN_VERIFICATION PRIMARY KEY (VERIFICATION_ID),
    CONSTRAINT FK_SLV_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES TB_STUDENT (STUDENT_ID),
    CONSTRAINT CK_SLV_STATUS CHECK (VERIFICATION_STATUS IN ('PENDING', 'CONSUMED', 'INVALIDATED', 'LOCKED'))
);

CREATE INDEX IDX_SLV_STUDENT_ID ON TB_STUDENT_LOGIN_VERIFICATION (STUDENT_ID, CREATED_AT);

COMMIT;
