-- 일반 로그인으로 만든 범위 없는 세션만 지운 뒤 컬럼을 되돌린다.
-- 초대 링크로 만든 기존 세션(TEACHER_STUDENT_ACCESS_ID가 있는 행)은 남긴다.
-- 이미 범위 없는 세션을 운영에서 쓰기 시작했다면 그 로그인 상태는 사라진다.

DELETE FROM TB_STUDENT_ACCESS_SESSION
WHERE TEACHER_STUDENT_ACCESS_ID IS NULL;

ALTER TABLE TB_STUDENT_ACCESS_SESSION DROP CONSTRAINT FK_SAS_STUDENT;
DROP INDEX IDX_SAS_STUDENT_ID;

ALTER TABLE TB_STUDENT_ACCESS_SESSION MODIFY (TEACHER_STUDENT_ACCESS_ID NOT NULL);
ALTER TABLE TB_STUDENT_ACCESS_SESSION DROP COLUMN STUDENT_ID;

DROP TABLE TB_STUDENT_LOGIN_VERIFICATION;
DROP SEQUENCE SEQ_STUDENT_LOGIN_VERIFICATION;

COMMIT;
